#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,16.9,1
#
gameConsoleRTOS.xem4f: package/cfg/gameConsoleRTOS.xem4f.mak

clean::
	-$(RM) package/cfg/gameConsoleRTOS.xem4f.mak
